import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFileSync } from "node:fs";

const isProductionBuild = process.argv[2] === "production";

const bundledFileBanner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const copyStylesPlugin = {
  name: "copy-styles",
  setup(build) {
    build.onEnd(() => {
      copyFileSync("./src/styles.css", "./styles.css");
    });
  },
};

const buildContext = await esbuild.context({
  banner: { js: bundledFileBanner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: isProductionBuild ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: isProductionBuild,
  plugins: [copyStylesPlugin],
});

if (isProductionBuild) {
  await buildContext.rebuild();
  await buildContext.dispose();
  console.log("Build complete -> main.js + styles.css");
} else {
  await buildContext.watch();
  console.log("Watching... (Ctrl+C to stop)");
}
